module.exports = {
     index: "immo_cities",
     type: "immo_cities",
     keys: ["name", "department"],
     mapping: {
         lastimportdate: { type: "date", format: "strict_date_optional_time||epoch_millis" },
         name: { type: "string", index: "not_analyzed" },
         url: { type: "string", index: "not_analyzed" },
         region: { type: "string", index: "not_analyzed" },
         department: { type: "string", index: "not_analyzed" },
         code_postal: { type: "integer" },
         code_insee: { type: "integer" },
         population: { type: "integer" },
         densite: { type: "double" },
         chomage: { type: "double" },
         superficie: { type: "double" },
         geopoint: {  type : "geo_point" },
         score_global: { type: "double" },
         score_qualite_vie_cadre_de_vie: { type: "double" },
         score_qualite_vie_espace_vert: { type: "double" },
         score_qualite_vie_proprete_rue: { type: "double" },
         score_qualite_vie_absence_pollution: { type: "double" },
         score_qualite_vie_niveau_securite: { type: "double" },
         score_qualite_vie: { type: "double" },
         score_economie_dynamisme_emploi: { type: "double" },
         score_economie_creation_entreprise: { type: "double" },
         score_economie: { type: "double" },
         score_logement_prix_immobilier: { type: "double" },
         score_logement_politique_renovation: { type: "double" },
         score_logement: { type: "double" },
         score_impot_niveau_taxe_habitation: { type: "double" },
         score_impot_niveau_taxe_fonciere: { type: "double" },
         score_impot: { type: "double" },
         score_education_densite_ecole: { type: "double" },
         score_education_densite_college: { type: "double" },
         score_education_densite_lycee: { type: "double" },
         score_education_proximite_universite: { type: "double" },
         score_education: { type: "double" },
         score_sport_loisir_qualite_musee: { type: "double" },
         score_sport_loisir_densite_cinema: { type: "double" },
         score_sport_loisir_densite_equipement_sportif: { type: "double" },
         score_sport_loisir: { type: "double" },
         score_tourisme_beaute_site_naturel: { type: "double" },
         score_tourisme_beaute_monument_architecture: { type: "double" },
         score_tourisme_mise_en_valeur_patrimoine: { type: "double" },
         score_tourisme_accueil_touriste: { type: "double" },
         score_tourisme: { type: "double" },
         score_transport_qualite_transport_commun: { type: "double" },
         score_transport_frequence_transport_commun: { type: "double" },
         score_transport_qualite_reseau_routier: { type: "double" },
         score_transport_facilite_stationnement: { type: "double" },
         score_transport_fluidite_traffic_automobile: { type: "double" },
         score_transport: { type: "double" },
         score_all: { type: "double" }
     },
     connection : {
         host: '127.0.0.1:9200'
     }
}